# Generated by Django 5.1.1 on 2024-12-19 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_field', to='pages.field'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='covers/default.png', upload_to='covers/'),
        ),
    ]
